general:
  output_directory: output
  sim_name: test_sim
  log_file: obscura.log
  log_to_console: true
  input_file_path: "/workspace/inputfiles/sample.stl"
  output_file_path: "/workspace/output/render_sample.png"

object_settings:
  mesh_scale: [1.0, 1.0, 1.0]
  mesh_location: [0.0, 0.0, 0.0]
  rotation: [0, 0, 0]

background_color: [1, 1, 1, 1]

material:
  material_color: [0.07, 0.28, 0.55, 1]
  material_roughness: 0.5
  material_metallic: 0.0

light:
  key_light_intensity: 3
  fill_light_intensity: 1.25
  ambient_light_strength: 0.2

camera:
  lens: 35
  type: PERSP

render:
  preview:
    mode: false
    resolution_x: 960
    resolution_y: 600
    engine: CYCLES # 'BLENDER_EEVEE_NEXT', 'CYCLES'
    samples: 32 # For CYCLES
    use_denoising: true # For CYCLES

  resolution_x: 1920
  resolution_y: 1200
  engine: CYCLES # 'BLENDER_EEVEE_NEXT', 'CYCLES'
  samples: 128 # For CYCLES
