general:
  output_directory: output
  sim_name: test_sim
  log_file: obscura.log
  log_to_console: true

paths:
  input_file: "/workspace/inputfiles/sample.stl"
  output_file: "/workspace/output/render_sample.png"

object_settings:
  mesh_scale: #array
    - 1.0
    - 1.0
    - 1.0
  mesh_location: #translation of the object in 3D space (x, y, z)
    - 0.0
    - 0.0
    - 0.0

  rotation: #degrees to be converted into rad in the parametric_render file
    - 0
    - 0
    - 0

material:
  material_color:
    - 0.07
    - 0.28
    - 0.55
    - 1
  material_roughness: 0.5
  material_metallic: 0.0

camera:
  camera_lens: 35
  camera_type: PERSP

light:
  key_light_intensity: 3
  fill_light_intensity: 1.25
  ambient_light_strength: 0.2

background_color:
  - 1
  - 1
  - 1
  - 1

render:
  render_resolution_x: 1920
  render_resolution_y: 1200
  render_engine: CYCLES # 'BLENDER_EEVEE_NEXT', 'CYCLES'
  samples: 128 # For CYCLES

preview:
  preview_mode: false
  preview_resolution_x: 960
  preview_resolution_y: 600
  preview_engine: CYCLES # 'BLENDER_EEVEE_NEXT', 'CYCLES'
  preview_samples: 32 # For CYCLES
  preview_use_denoising: true # For CYCLES
